### ISSUE TITLE
Geo::Line centroid doesn't work for straight lines

### ISSUE THREAD

**Issue by cyga** [markov2/perl5-Geo-Point#1]
For example:
* any 2 points
* 3 and more points on the same line

Also line has to be closed for polygon methods to work.

**Comment by markov2** [comment]
For two points, I can imagine how to compute the center.  However, what would be the formula for a multi-point line?  The point which has the average smallest distance to all points?  The middle of the extremes?  When I add very small values to any one of the points, it gives "unstable" results.

**Comment by cyga** [comment]
As far as I understand:
1. centroid is a center of mass
2. centroid for given points is simply average for each coordinate (not only for Decart's, but even for polar? not quite sure, but looks like it).
3. for a polygon we have all the area with weight, that's why formula is different.
4. for a line we have all the points of the line with weight. does it make sense?

Therefore, formula for a line has to differ from 2nd and 3rd cases. Am I right?
How about:
* get middle point for each segment of a line
* get average for the points
Would it be the center of the mass for initial line?

I came to this library with streets given by number of points really. And I was thinking of centroids for streets. And I don't know the answer to what is the center of the street yet? Because I want center to be on the street. May be, I can use center of the mass for corresponding line and get nearest point at the street to it?

**Comment by markov2** [comment]
* Alex Sudakov (notifications@github.com) [181115 10:17]:
> As far as I understand:
> 1. centroid is a center of mass

Yes

> 2. centroid for given points is simply average for each coordinate (not
> only for Decart's, but even for polar? not quite sure, but looks like it).

No, that's only for "point weights", but not for connected points.

> 3. for a polygon we have all the area with weight, that's why formula
>    is different.

The centroid always is about weight.  Some shapes are simpler, so make
the formula simpler.

> 4. for a line we have all the points of the line with weight. does it
>    make sense?

You cannot really speak about "center of weight" when the shape is one-
dimensional: the weight is 0.  That's why you do not get a result.

> Therefore, formula for a line has to differ from 2nd and 3rd cases. Am
> I right?
> How about:
> * get middle point for each segment of a line
> * get average for the points
> Would it be the center of the mass for initial line?

Math exercise: put "lim dx->0  [x1+dx, y1], [x2+dx, y2], ..." in the
formula ;-)

> I came to this library with streets given by number of points
> really. And I was thinking of centroids for streets. And I don't know the
> answer to what is the center of the street yet? Because I want center to
> be on the street. May be, I can use center of the mass for corresponding.
> line and get nearest point at the street to it?

Point with smallest average distance to the houses (where each point is
a house)?  Point in the middle between the start and end of the street?
In either case not a polygon (2D) but a line (1D)
-- 
greetz,
               MarkOv

------------------------------------------------------------------------
drs Mark A.C.J. Overmeer                                MARKOV Solutions
       Mark@Overmeer.net                          solutions@overmeer.net
http://Mark.Overmeer.net                   http://solutions.overmeer.net

**Comment by cyga** [comment]
> You cannot really speak about "center of weight" when the shape is one-
> dimensional: the weight is 0.  That's why you do not get a result.

No. For me it looks like your statement has number of errors.
First, what do you call one dimensional? Line segment in a plain, do you call it "one dimensional"?
Or if we consider a line consisting of number of segments (not straight always). Is it still "one dimensional"? Don't you confuse "area" and "1D/2D"?
Second, get a stick (line segment), it has weight. Center of the mass right in the middle of the segment.

> Math exercise: put "lim dx->0  [x1+dx, y1], [x2+dx, y2], ..." in the formula ;-)

That's because you consider polygon and corresponding formula, but, as I wrote in the subject, I asked about Geo::Line ("Line"). So, it looks like, it was bad naming. Your Geo::Line is Geo::Contour really (border as a variant).
Well, therefore it doesn't make sense to discuss or implement it here.

> In either case not a polygon (2D) but a line (1D)

"line". You have Geo::Line consisting of Geo::Point s. But you always treat it as polygon or figure with non zero area.
