### ISSUE TITLE
Point-to-Point distance calculation incorrect

### ISSUE THREAD

**Issue by haukex** [markov2/perl5-Geo-Point#3]
As can be seen in the code below, the distance reported between two points is off by almost two km. If I swap latitude and longitude of the points, the answer is much closer to the correct answer.

```perl
use warnings;
use strict;
use Geo::Point;

print "Google Earth says: 4034m\n";
# https://www.cqsrg.org/tools/GCDistance/ also reports the same

my $pt1 = Geo::Point->new(long=>'13.00029029994476', lat=>'53.14435999160158', proj=>'wgs84');
my $pt2 = Geo::Point->new(long=>'13.04926295660808', lat=>'53.16551529994161', proj=>'wgs84');
print $pt1->distance( $pt2, 'meter' ), "\n";  # => 5908.73480662019 (wrong)

my $pt3 = Geo::Point->new(lat=>'13.00029029994476', long=>'53.14435999160158', proj=>'wgs84');
my $pt4 = Geo::Point->new(lat=>'13.04926295660808', long=>'53.16551529994161', proj=>'wgs84');
print $pt3->distance( $pt4, 'meter' ), "\n";  # => 4024.89986717665 (nearly right)
```

**Comment by markov2** [comment]
I should have released Geo::Point 0.99... but totally forgot about it: fixed that now.  It moves from Geo::Distance (deprecated) to GIS::Distance which may support more algorithms.

The Google Earth projection is a bit sloppy for speed (when I remember correctly).  I do not know whether that is reflected in their distance computation as well.
